require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductUnitsController do

  # This should return the minimal set of attributes required to create a valid
  # ProductUnit. As you add validations to ProductUnit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "game" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductUnitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all product_units as @product_units" do
      product_unit = ProductUnit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:product_units).should eq([product_unit])
    end
  end

  describe "GET show" do
    it "assigns the requested product_unit as @product_unit" do
      product_unit = ProductUnit.create! valid_attributes
      get :show, {:id => product_unit.to_param}, valid_session
      assigns(:product_unit).should eq(product_unit)
    end
  end

  describe "GET new" do
    it "assigns a new product_unit as @product_unit" do
      get :new, {}, valid_session
      assigns(:product_unit).should be_a_new(ProductUnit)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_unit as @product_unit" do
      product_unit = ProductUnit.create! valid_attributes
      get :edit, {:id => product_unit.to_param}, valid_session
      assigns(:product_unit).should eq(product_unit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductUnit" do
        expect {
          post :create, {:product_unit => valid_attributes}, valid_session
        }.to change(ProductUnit, :count).by(1)
      end

      it "assigns a newly created product_unit as @product_unit" do
        post :create, {:product_unit => valid_attributes}, valid_session
        assigns(:product_unit).should be_a(ProductUnit)
        assigns(:product_unit).should be_persisted
      end

      it "redirects to the created product_unit" do
        post :create, {:product_unit => valid_attributes}, valid_session
        response.should redirect_to(ProductUnit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_unit as @product_unit" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductUnit.any_instance.stub(:save).and_return(false)
        post :create, {:product_unit => { "game" => "invalid value" }}, valid_session
        assigns(:product_unit).should be_a_new(ProductUnit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductUnit.any_instance.stub(:save).and_return(false)
        post :create, {:product_unit => { "game" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_unit" do
        product_unit = ProductUnit.create! valid_attributes
        # Assuming there are no other product_units in the database, this
        # specifies that the ProductUnit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductUnit.any_instance.should_receive(:update_attributes).with({ "game" => "" })
        put :update, {:id => product_unit.to_param, :product_unit => { "game" => "" }}, valid_session
      end

      it "assigns the requested product_unit as @product_unit" do
        product_unit = ProductUnit.create! valid_attributes
        put :update, {:id => product_unit.to_param, :product_unit => valid_attributes}, valid_session
        assigns(:product_unit).should eq(product_unit)
      end

      it "redirects to the product_unit" do
        product_unit = ProductUnit.create! valid_attributes
        put :update, {:id => product_unit.to_param, :product_unit => valid_attributes}, valid_session
        response.should redirect_to(product_unit)
      end
    end

    describe "with invalid params" do
      it "assigns the product_unit as @product_unit" do
        product_unit = ProductUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_unit.to_param, :product_unit => { "game" => "invalid value" }}, valid_session
        assigns(:product_unit).should eq(product_unit)
      end

      it "re-renders the 'edit' template" do
        product_unit = ProductUnit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductUnit.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_unit.to_param, :product_unit => { "game" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_unit" do
      product_unit = ProductUnit.create! valid_attributes
      expect {
        delete :destroy, {:id => product_unit.to_param}, valid_session
      }.to change(ProductUnit, :count).by(-1)
    end

    it "redirects to the product_units list" do
      product_unit = ProductUnit.create! valid_attributes
      delete :destroy, {:id => product_unit.to_param}, valid_session
      response.should redirect_to(product_units_url)
    end
  end

end
