require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransportBatchesController do

  # This should return the minimal set of attributes required to create a valid
  # TransportBatch. As you add validations to TransportBatch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "product_batch" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransportBatchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all transport_batches as @transport_batches" do
      transport_batch = TransportBatch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transport_batches).should eq([transport_batch])
    end
  end

  describe "GET show" do
    it "assigns the requested transport_batch as @transport_batch" do
      transport_batch = TransportBatch.create! valid_attributes
      get :show, {:id => transport_batch.to_param}, valid_session
      assigns(:transport_batch).should eq(transport_batch)
    end
  end

  describe "GET new" do
    it "assigns a new transport_batch as @transport_batch" do
      get :new, {}, valid_session
      assigns(:transport_batch).should be_a_new(TransportBatch)
    end
  end

  describe "GET edit" do
    it "assigns the requested transport_batch as @transport_batch" do
      transport_batch = TransportBatch.create! valid_attributes
      get :edit, {:id => transport_batch.to_param}, valid_session
      assigns(:transport_batch).should eq(transport_batch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransportBatch" do
        expect {
          post :create, {:transport_batch => valid_attributes}, valid_session
        }.to change(TransportBatch, :count).by(1)
      end

      it "assigns a newly created transport_batch as @transport_batch" do
        post :create, {:transport_batch => valid_attributes}, valid_session
        assigns(:transport_batch).should be_a(TransportBatch)
        assigns(:transport_batch).should be_persisted
      end

      it "redirects to the created transport_batch" do
        post :create, {:transport_batch => valid_attributes}, valid_session
        response.should redirect_to(TransportBatch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transport_batch as @transport_batch" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBatch.any_instance.stub(:save).and_return(false)
        post :create, {:transport_batch => { "product_batch" => "invalid value" }}, valid_session
        assigns(:transport_batch).should be_a_new(TransportBatch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBatch.any_instance.stub(:save).and_return(false)
        post :create, {:transport_batch => { "product_batch" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transport_batch" do
        transport_batch = TransportBatch.create! valid_attributes
        # Assuming there are no other transport_batches in the database, this
        # specifies that the TransportBatch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransportBatch.any_instance.should_receive(:update_attributes).with({ "product_batch" => "" })
        put :update, {:id => transport_batch.to_param, :transport_batch => { "product_batch" => "" }}, valid_session
      end

      it "assigns the requested transport_batch as @transport_batch" do
        transport_batch = TransportBatch.create! valid_attributes
        put :update, {:id => transport_batch.to_param, :transport_batch => valid_attributes}, valid_session
        assigns(:transport_batch).should eq(transport_batch)
      end

      it "redirects to the transport_batch" do
        transport_batch = TransportBatch.create! valid_attributes
        put :update, {:id => transport_batch.to_param, :transport_batch => valid_attributes}, valid_session
        response.should redirect_to(transport_batch)
      end
    end

    describe "with invalid params" do
      it "assigns the transport_batch as @transport_batch" do
        transport_batch = TransportBatch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBatch.any_instance.stub(:save).and_return(false)
        put :update, {:id => transport_batch.to_param, :transport_batch => { "product_batch" => "invalid value" }}, valid_session
        assigns(:transport_batch).should eq(transport_batch)
      end

      it "re-renders the 'edit' template" do
        transport_batch = TransportBatch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBatch.any_instance.stub(:save).and_return(false)
        put :update, {:id => transport_batch.to_param, :transport_batch => { "product_batch" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transport_batch" do
      transport_batch = TransportBatch.create! valid_attributes
      expect {
        delete :destroy, {:id => transport_batch.to_param}, valid_session
      }.to change(TransportBatch, :count).by(-1)
    end

    it "redirects to the transport_batches list" do
      transport_batch = TransportBatch.create! valid_attributes
      delete :destroy, {:id => transport_batch.to_param}, valid_session
      response.should redirect_to(transport_batches_url)
    end
  end

end
