require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorksheetsController do

  # This should return the minimal set of attributes required to create a valid
  # Worksheet. As you add validations to Worksheet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "game" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorksheetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all worksheets as @worksheets" do
      worksheet = Worksheet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:worksheets).should eq([worksheet])
    end
  end

  describe "GET show" do
    it "assigns the requested worksheet as @worksheet" do
      worksheet = Worksheet.create! valid_attributes
      get :show, {:id => worksheet.to_param}, valid_session
      assigns(:worksheet).should eq(worksheet)
    end
  end

  describe "GET new" do
    it "assigns a new worksheet as @worksheet" do
      get :new, {}, valid_session
      assigns(:worksheet).should be_a_new(Worksheet)
    end
  end

  describe "GET edit" do
    it "assigns the requested worksheet as @worksheet" do
      worksheet = Worksheet.create! valid_attributes
      get :edit, {:id => worksheet.to_param}, valid_session
      assigns(:worksheet).should eq(worksheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Worksheet" do
        expect {
          post :create, {:worksheet => valid_attributes}, valid_session
        }.to change(Worksheet, :count).by(1)
      end

      it "assigns a newly created worksheet as @worksheet" do
        post :create, {:worksheet => valid_attributes}, valid_session
        assigns(:worksheet).should be_a(Worksheet)
        assigns(:worksheet).should be_persisted
      end

      it "redirects to the created worksheet" do
        post :create, {:worksheet => valid_attributes}, valid_session
        response.should redirect_to(Worksheet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved worksheet as @worksheet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Worksheet.any_instance.stub(:save).and_return(false)
        post :create, {:worksheet => { "game" => "invalid value" }}, valid_session
        assigns(:worksheet).should be_a_new(Worksheet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Worksheet.any_instance.stub(:save).and_return(false)
        post :create, {:worksheet => { "game" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested worksheet" do
        worksheet = Worksheet.create! valid_attributes
        # Assuming there are no other worksheets in the database, this
        # specifies that the Worksheet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Worksheet.any_instance.should_receive(:update_attributes).with({ "game" => "" })
        put :update, {:id => worksheet.to_param, :worksheet => { "game" => "" }}, valid_session
      end

      it "assigns the requested worksheet as @worksheet" do
        worksheet = Worksheet.create! valid_attributes
        put :update, {:id => worksheet.to_param, :worksheet => valid_attributes}, valid_session
        assigns(:worksheet).should eq(worksheet)
      end

      it "redirects to the worksheet" do
        worksheet = Worksheet.create! valid_attributes
        put :update, {:id => worksheet.to_param, :worksheet => valid_attributes}, valid_session
        response.should redirect_to(worksheet)
      end
    end

    describe "with invalid params" do
      it "assigns the worksheet as @worksheet" do
        worksheet = Worksheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Worksheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => worksheet.to_param, :worksheet => { "game" => "invalid value" }}, valid_session
        assigns(:worksheet).should eq(worksheet)
      end

      it "re-renders the 'edit' template" do
        worksheet = Worksheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Worksheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => worksheet.to_param, :worksheet => { "game" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested worksheet" do
      worksheet = Worksheet.create! valid_attributes
      expect {
        delete :destroy, {:id => worksheet.to_param}, valid_session
      }.to change(Worksheet, :count).by(-1)
    end

    it "redirects to the worksheets list" do
      worksheet = Worksheet.create! valid_attributes
      delete :destroy, {:id => worksheet.to_param}, valid_session
      response.should redirect_to(worksheets_url)
    end
  end

end
